name: "Run a command and flush stdout"
description: "Helper to flush the stdout buffer in case a command ends abruptly."

inputs:
  cmd-exec:
    description: Command to execute
    required: true
  cmd-args:
    description: Arguments to the command line
    required: false
    default: ""
  working-directory:
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - name: Run
      working-directory: ${{ inputs.working-directory }}
      shell: pwsh
      run: |
        $proc = Start-Process -NoNewWindow -PassThru -FilePath ${{ inputs.cmd-exec }} -ArgumentList '${{ inputs.cmd-args }}'
        # WaitForExit() below instead of -Wait'ing above because the latter waits for subprocesses
        # as well, and costs about 10m of wall time on CI.
        # See https://thebrowsercompany.slack.com/archives/C05PPA14338/p1693343561057779 for details.
        $proc.WaitForExit()
        [Console]::Out.Flush()
        exit $proc.ExitCode
